### ISSUE TITLE
flag support for _just_ prd or _just_ dev deps?

### ISSUE THREAD

**Issue by cdaringe** [Snyk/resolve-deps#24]
hello:

i have a desire to yield the dep tree for _just_ prd, and then again for just _devDeps_.  is that a thing™?  if not, could it be a thing with relative ease?

**Comment by gjvis** [comment]
Hi @cdaringe,

It's not supported currently, and its not currently needed for our internal use-case so we're unlikely to get to it soon. We do accept pull-requests (see [CONTRIBUTING.md](https://github.com/Snyk/resolve-deps/blob/develop/CONTRIBUTING.md) for contribution guidelines), if you'd like to extend this yourself.

**Comment by cdaringe** [comment]
sure enough, you guys actually already did the hard work for me!  there's a `depType` key, which yields `"prod"` or `"dev"`.  i simply picked the `"dev"` ones out of the root and had what I needed!

thanks for the lib!

**Comment by gjvis** [comment]
awesome 👍 😁
