### ISSUE TITLE
consider dropping es6-promise

### ISSUE THREAD

**Issue by cdaringe** [snyk/resolve-deps#27]
TIL that es6-promise doesn't emit `unhandledRejection` events, which is super bummery.  ref: https://github.com/stefanpenner/es6-promise/issues/70

this came up because some tests i wrote wrapping resolve-deps were failing, but not chugging through my error handler.

**Comment by adrukh** [comment]
Thanks @cdaringe 

The benefit of using `es6-promise` is mainly for Node.js 0.12 users. Right now my preference is to properly support older (but not EOL-ed) versions of Node.js with this package.

**Comment by cdaringe** [comment]
Ya that makes sense!  Im wondering if a different lib however is also backwards compatible and well behaved
