### ISSUE TITLE
incorrect depType being reported

### ISSUE THREAD

**Issue by cdaringe** [snyk/resolve-deps#28]
# problem statement

please see explanation and example @ https://github.com/cdaringe/snyk-resolve-deps-dep-type-bug

thx!

**Comment by cdaringe** [comment]
i suppose this may? be impossible to resolve in the current implementation.  the resultant dep report comes back in POJO, keyed by module names.  if conflicting module names exist in deps/devDeps, one must take precedence.  i've been re-keying things in my reports by `${name}${delim}${version}` s.t. all cases can be considered.

hmm.

**Comment by gjvis** [comment]
Interesting case, and great bug report. Thanks! We'll look into this (although I can't promise an particular fix time-frame).

**Comment by ypicard** [comment]
Hello from the future,

I know you did not promise a particular fix time-frame, but should we still expect an update anytime soon?

We still do not have flying cars, so you're not missing out on anything!
