### ISSUE TITLE
Use `lodash` as a dep directly

### ISSUE THREAD

**Issue by lili2311** [snyk/resolve-deps#55]
### Description
- Use lodash as a package directly and drop this https://github.com/snyk/resolve-deps/blob/master/lib/lodash.ts#L1
- `npm i lodash`
- delete the custom code and use the installed package instead
- update `import * as _ from './lodash';` to use the package directly like so `import * as _ from 'lodash';`

**Comment by deneuv34** [comment]
Hi @lili2311, can I take this issue? :D

**Comment by FauxFaux** [comment]
Fixed in #56.
